### ISSUE TITLE
quest not working

### ISSUE THREAD

**Issue by kida-cakes** [decentraland/issues#37] opened 2021-10-11 11:46 UTC
### What happened?

i did the steampunk quest and the last step is to talk to anna yet she says your reward is waiting for you/ hope you enjoyed but the box doesnt get ticked and i'm unable to finish and get my POAP. As well having problems with the dragon city quest, i'm only missing the final trial yet i don't have the square shape and therefore unable to do the last step...

### Steps to reproduce

i have no idea how to fix this

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

### Wallet

Metamask

### CPU

2.8 GHz Quad-Core Intel Core i7

### GPU

AMD Radeon Pro 555 OpenGL Engine 512MB

### RAM

16 GB 

### Kernel Version

1.0.0-1323785730.commit-254c3e6

### Unity Version

1.0.15786-20211007111955.commit-f13e5dd

### Realm

fenrir

### NameTag

Kida#f720

**Comment by nearnshaw** [comment] 2021-11-08 21:02
Hi!

The issue with the DappCraft quest has now been resolved, thanks for reporting.

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12

Regarding the dragon city quest, I'm not able to reproduce it. Does the final piece still not appear after revisiting the scene?

**Comment by moliva** [comment] 2022-06-28 14:50
Closing this issue because of not having a response for two weeks and the feature is currently not enabled in the platform.

**Closed as completed by moliva** 2022-06-28 14:50 UTC
Labels: quests
