### ISSUE TITLE
Crash I was mining a meteor 

### ISSUE THREAD

**Issue by jasongutt** [decentraland/issues#565] opened 2022-11-16 19:15 UTC
### What happened?

Crashed I was mining a meteor in the desktop app and watching youtube 

Something went wrong
Renderer unexpected exit: Exit code c0000005, error message: Command failed: C:\Users\Jason\AppData\Roaming\explorer-desktop-launcher\renderer\prod\unity-renderer-windows.exe --browser false --port 7666

### Steps to reproduce

Crashed I was mining a meteor in the desktop app and watching youtube 

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz

### GPU

AMD Radeon(TM) R9 290X 4072MB

### RAM

12175MB

### Kernel Version

1.0.0-3482189927.commit-83faef0

### Unity Version

desktop-1.0.805-20221116144427.commit-ad3486c

### Realm

artemis

### NameTag

CyberNinja#4389

**Comment by kwspgoliasz** [comment] 2022-11-17 12:13
Hi, thank you for contacting us. This crash might be caused by outdated drivers, especially for the graphics card. Could you try to install all of the latest drivers for your hardware and afterwards reinstall the Decentraland client?
If these methods won't fix the issue, please contact us again.

**Comment by kwspgoliasz** [comment] 2022-12-01 14:23
Closing the ticket due to lack of response for two weeks. In case of any further questions, please don't hesitate to contact us again.

**Closed as completed by kwspgoliasz** 2022-12-01 14:23 UTC
Labels: explorer, pending response
