### ISSUE TITLE
Is Decentraland a single player game?

### ISSUE THREAD

**Issue by dreamerhew** [decentraland/issues#233] opened 2021-12-25 14:15 UTC
### What happened?

I cant saw any other player
![image](https://user-images.githubusercontent.com/79210907/147386862-2e78ca5b-f9ae-4b14-87e4-4e9e3292c52f.png)

### Steps to reproduce

I can only saw myself

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

AMD Ryzen 9 5900HX with Radeon Graphics

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7219) 512MB

### RAM

32GB

### Kernel Version

1.0.0-1615749195.commit-a4079d2

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

baldr

### NameTag

YUME#6cbe

**Comment by 0xJuancito** [comment] 2022-06-28 14:46
duplicate of https://github.com/decentraland/issues/issues/235

**Closed as completed by 0xJuancito** 2022-06-28 14:46 UTC
Labels: duplicate, platform, sdk
