### ISSUE TITLE
Decentraland without players

### ISSUE THREAD

**Issue by LoufIke** [decentraland/issues#135] opened 2021-11-25 19:45 UTC
### What happened?

Hi,

I don't why I'm alone in Decentraland, I tried to meet someone but it seems like I'm alone in every places.

I cannot play in multiplayer mode, what can I do?

Best regards,

### Steps to reproduce

I don't know ...

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

### Wallet

Wallet Connect

### CPU

2 GHz Intel Core i5 quatre cœurs

### GPU

Intel Iris Plus Graphics 1536 Mo

### RAM

2 GHz Intel Core i5 quatre cœurs

### Kernel Version

1.0.0-1503886844.commit-b174d3b

### Unity Version

1.0.20096-20211118122248.commit-bfbdade

### Realm

loki

### NameTag

Romzy#e3f9

**Comment by 0xJuancito** [comment] 2022-06-28 14:53
duplicate of https://github.com/decentraland/issues/issues/193

**Closed as completed by 0xJuancito** 2022-06-28 14:53 UTC
Labels: duplicate, platform
