### ISSUE TITLE
Cannot see other players

### ISSUE THREAD

**Issue by renkcub** [decentraland/issues#261] opened 2022-01-12 20:52 UTC
### What happened?

Cannot see other players in game, unless their avatar has been customized such as in The Wilderness P2E.

Have tried switching islands, realms, restarting PC, resetting + reconnecting metamask, all browser settings, router/modem reset turn off firewall/vpn, optimizing and minimizing graphics settings and hardware acceleration. Tried another PC (same metamask seed). not i cannot see players whatsoever, the avatars models in the wilderness are totally different for the P2E game than the default decentraland player models, and that is only place ive successfully seen other players. I can see them having some action in decentral games casino, but not their player model themselves. see Imgur link in reply.

### Steps to reproduce

unknown

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

### Wallet

Metamask

### CPU

i7-10510u

### GPU

ANGLE (NVIDIA, NVIDIA GeForce MX330 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6280) 512MB

### RAM

16

### Kernel Version

1.0.0-1682491587.commit-afd06bd

### Unity Version

1.0.24303-20220111173830.commit-edbd3c9

### Realm

dg

### NameTag

tester123451#a98b

**Comment by renkcub** [comment] 2022-01-12 20:53
not i cannot see players whatsoever, the avatars models in the wilderness are totally different for the P2E game than the default decentraland player models.

**Comment by renkcub** [comment] 2022-01-12 21:10
https://imgur.com/a/TYTwMGe

**Comment by olavra** [comment] 2022-02-08 20:29
Hi @renkcub 

Sorry for the late response. Are you still experiencing this issue?

**Comment by renkcub** [comment] 2022-02-08 20:33
On Chrome, yes. I was able to workaround it by using Brave.

**Comment by 0xJuancito** [comment] 2022-06-28 14:48
Can you provide us with more information to debug this issue?

Steps to reproduce, coordinates of the parcels, realm where it happens

**Comment by 0xJuancito** [comment] 2022-06-28 14:59
closing as duplicate of https://github.com/decentraland/issues/issues/193

Please add any relevant information to that issue to help debug the problem

**Closed as completed by 0xJuancito** 2022-06-28 14:59 UTC
Labels: duplicate, platform, sdk

**Comment by renkcub** [comment] 2022-07-06 19:09
happens everywhere using chrome. didnt before. doesnt matter what realm. no
steps--> always happens using chrome.
