### ISSUE TITLE
Asset Transfering Issue

### ISSUE THREAD

**Issue by acrosscoder** [decentraland/issues#637] opened 2023-05-05 03:22 UTC
### What happened?

I cannot transfer a wearable to another wallet  and I cant purchase a wearable....it keeps showing this message 
![image](https://user-images.githubusercontent.com/39716656/236370980-118b8c7d-19d2-413f-9dac-913b04702315.png)

I saw this happen to DCL streamers sometimes but Im not sure why it keeps happening

### Steps to reproduce
![cannottransfer](https://user-images.githubusercontent.com/39716656/236371450-467a3dd3-0cac-4d48-8bb8-3feb6e919d87.gif)

Go to DCL marketplace and try transferring or purchasing a  wearable
 without switching network

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 7 CPU

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32GB

### Kernel Version

1.0.108984-20230503134246.commit-eadea75

### Unity Version

1.0.108984-20230503134246.commit-eadea75

### Realm

heimdallr

### NameTag

JimSedric

**Comment by juanmahidalgo** [comment] 2023-05-11 11:20
This is the expected behavior. It happens when the gas price in Polygon's network is too high and we can't afford to give free txs to our users. As the error shows, the workaround is to switch networks and pay for the tx. You can read more about in clicking the "Learn more" link in the error message. Closing the issue for now, please let us know if you have any doubts!

**Comment by juanmahidalgo** [comment] 2023-05-11 11:39
@acrosscoder can you check if if it's happening please? I cannot reproduce it with the steps provided.

**Comment by kwssbocian** [comment] 2023-06-23 09:51
Closing this issue due to a lack of response for over two weeks.

**Closed as completed by kwssbocian** 2023-06-23 09:51 UTC
Labels: new, explorer
