### ISSUE TITLE
cant see other player

### ISSUE THREAD

**Issue by samannavaie** [decentraland/issues#235] opened 2021-12-25 21:47 UTC
### What happened?

I cant see anybody any of the event.i try too chnage my realm url but its not help.and i see santa prise and cant claim it.

### Steps to reproduce

mail me or guid me.or solve it!

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Wallet

Metamask

### CPU

Intel(R) Pentium(R) CPU G630 @ 2.70GHz   2.70 GHz

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 630 Direct3D11 vs_5_0 ps_5_0, D3D11-23.21.13.8813) 512MB

### RAM

4

### Kernel Version

1.0.0-1615749195.commit-a4079d2

### Unity Version

1.0.23155-20211222192146.commit-63835fd

### Realm

dg

### NameTag

saman#0635

**Comment by 0xJuancito** [comment] 2022-06-28 14:50
duplicate of https://github.com/decentraland/issues/issues/261

**Closed as completed by 0xJuancito** 2022-06-28 14:50 UTC
Labels: duplicate, platform, sdk
