### ISSUE TITLE
I saw that my proble still here (5 days now) 

### ISSUE THREAD

**Issue by BillionaireDA** [decentraland/issues#585] opened 2023-01-10 00:10 UTC
### What happened?

Unauthorized client error 

### Steps to reproduce

the same issue 

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz

### GPU

NVIDIA GeForce GTX 1050 1977MB

### RAM

8132MB

### Kernel Version

2.0.0-3877361219.commit-077d5a2

### Unity Version

desktop-1.0.1045-20230104223520.commit-f7ff2ae

### Realm

athena

### NameTag

Pigeon#9a87

**Comment by kwssbocian** [comment] 2023-01-16 12:45
Closing as duplicate of #583.

**Closed as completed by kwssbocian** 2023-01-16 12:45 UTC
Labels: new, explorer
