### ISSUE TITLE
GolfCraft Timeouts

### ISSUE THREAD

**Issue by NavyCalcro** [decentraland/issues#212] opened 2021-12-16 21:20 UTC
### What happened?

In several attempts of GolfCraft (both Training and Competition), I was timed out and automatically failed.

### Steps to reproduce

Quite simply attempt any of the levels.

### Operating System

Chrome and Windows

### Wallet

Metamask

### CPU

Intel i7-10700K

### GPU

NVIDIA GeForce RTX 2070 SUPER 

### RAM

32

### Kernel Version

1.0.0-1589159435.commit-18ab21c

### Unity Version

1.0.22157-20211214200027.commit-064c9e0

### Realm

dg

### NameTag

ForeverDM#5235

**Comment by pabloes** [comment] 2022-04-26 22:56
The issue is not reproducible nowadays unless servers go down or any other remote circumstance. I would close this issue.

**Comment by D4rWiNSS** [comment] 2022-06-28 14:23
This can't be fixed on our end since this bug is related to the scene. The content creator should fix it. Please contact the content creator in order to have this issue fixed

**Closed as completed by D4rWiNSS** 2022-06-28 14:23 UTC
Labels: scene
