### ISSUE TITLE
Bug on the moove

### ISSUE THREAD

**Issue by QuentinDvl** [decentraland/issues#187] opened 2021-12-03 21:42 UTC
### What happened?

My avatar is mooving alone, i've try to reset the computer, the game but he still moving alone ... I've try to diconnect my keypad but he still moove ... i don't understand

### Steps to reproduce

Just try to stop him aha

### Operating System

Chrome/96.0.4664.45

### Wallet

Metamask

### CPU

intel i7

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676) 512MB

### RAM

16GB

### Kernel Version

1.0.0-1527377120.commit-a94b988

### Unity Version

1.0.21334-20211202053601.commit-3d8e7ad

### Realm

dg

### NameTag

Quentin#1d06

**Comment by olavra** [comment] 2022-02-08 21:44
Hi @QuentinDvl 

We have detected this type of problem in people who have graphic tablets, use special mouse or have more than one input device connected at the same time.

Our latest updates should have solved this problem, but in case this is not your case, could you please extend your setup information?

Thanks

**Comment by LeDoofer** [comment] 2022-04-30 11:04
Still a problem if I launch using my default browser, Brave Browser. 
As if W key is permanently pressed. Only a problem on Decentraland - no problems/drift running other Unity programs, Google Earth etc. 

HOWEVER, if I use Microsoft Edge Version 101.0.1210.32 (Official build) (64-bit), it does NOT occur, there is no problem.

System details:

Dell XPS 15.
Device name	DESKTOP-RCHA2G1
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Device ID	C24598FE-2741-4BA0-9AE5-4BEA4240AC4E
Product ID	00330-51013-07615-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points
Edition	Windows 10 Pro
Version	21H2
Installed on	‎24/‎03/‎2021
OS build	19044.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by LeDoofer** [comment] 2022-04-30 11:16
Apologies, it worked via Edge once! Since that test, the problem (permanent W) has reappeared, whichever browser I use, however many times I re-launch browsers, reset the computer etc. This is clearly a Decentraland-specific problem.

**Comment by davidejensen** [comment] 2022-05-02 08:23
Hello @LeDoofer 
I'm sorry to hear that the issue is still happening after the latest fixes.

Do you know if there is the possibility of deactivating the Pen and touch support temporarely? If there is could you please try to deactivate it, restart your pc and try to open Decentraland to see if the walking problem happens again? 
This test would help us a lot to tackle the problem

Thanks in advance

**Comment by moliva** [comment] 2022-06-28 14:35
Closing this issue because of not having a response for two weeks.

**Closed as completed by moliva** 2022-06-28 14:35 UTC
Labels: explorer

**Comment by LeDoofer** [comment] 2022-10-11 07:16
Hi there.
In Device Manager, disabling the "HID compliant touchpad" & and/or "HID compliant touchscreen" drivers has no effect on the 'continuous running'.
Also in the HID list is "HID compliant game controller". Disabling this DOES stop the 'continuous running'. It requires a PC restart to disable it, but not to enable it. Thus it's easy to demonstrate that, on enabling this driver, the running starts again.
1. This driver is supplied by Microsoft, Version 10.0.19041.868, and exists "on 3Dconnexion KMJ Emulator" i.e. it's probably a driver that has something to do with my 3DConnexion Space Mouse. 
2. Connecting the Space Mouse does cause 'scroll creep' (= as if you are pressing 'down arrow' every second or so, or using a down scrollbar slowly) in programs with a vertical scroll bar e.g. Word, browsers. I leave it disconnected unless I'm using it (Blender, Google Earth), which stops the 'scroll creep'. 
3. Disabling the 'HID Compliant game controller' doesn't stop the Space Mouse from working when I plug it in. 
4. Plugging in the Space Mouse doesn't start the 'eternal running' - even when it's causing 'scroll creep' in other programs. So I'd guess the Space Mouse is actually using another driver (probably the one supplied by 3DConnexion), which doesn't cause the problems with Decentraland. This also perhaps indicates that Decentraland is clearly resistant to small calibration errors in this sort of input i.e. controllers that don't fully return to zero.
At least I (currently) have a reproducible way of causing, and stopping, this problem!
Let me know if there are any other experiments you'd like me to do.
Stuart


Sent from Mail for Windows
